### ISSUE TITLE
Cant Install Twig 2.1.1

### ISSUE THREAD

**Issue by xtensions** [pulse00/Twig-Eclipse-Plugin#104]
Hi

Getting errors installing twig on latest eclipse , Version: 2021-03 (4.19.0) Build id: 20210312-0638

Errors: 
The following solutions are not available: Twig Plugin 2.1.1 (id=com.dubture.twig.feature.feature.group, site=http://p2.pdt-extensions.org/)

See Video: https://drive.google.com/file/d/1IErJB3UbXyNis4SY8x8bZ9llmV8yvCvY/view?usp=sharing

<img width="817" alt="Screenshot 2021-05-07 at 12 55 15 PM" src="https://user-images.githubusercontent.com/14876525/117414309-9c472300-af34-11eb-9bb6-24f56d5dd16d.png">
<img width="881" alt="Screenshot 2021-05-07 at 12 54 34 PM" src="https://user-images.githubusercontent.com/14876525/117414319-9fdaaa00-af34-11eb-8c18-04298b7eda2c.png">

**Comment by o-alquimista** [comment]
Same here. The URL it's trying to access is returning code 403 "Forbidden".

http://dl.bintray.com/pulse00/pdt-extensions/release/2020-03/

**Comment by dhcpp4** [comment]
Same here

**Comment by zulus** [comment]
try p2-dev http://p2-dev.pdt-extensions.org/

**Comment by o-alquimista** [comment]
> try p2-dev http://p2-dev.pdt-extensions.org/

Sorry, how can I do that?
I thought you could fix the marketplace installation...

**Comment by xtensions** [comment]
> try p2-dev http://p2-dev.pdt-extensions.org/

Tried that already several times, do you have any other possible solution to suggest like sideload, or a jar file to install.

**Comment by dhcpp4** [comment]
Here are the Twig plugin files from my older installation of Eclipse. I placed them in the same locations as there, but new Eclipse doesn't see the plugin. I guess that in some config file the plugin should be referenced to, but I don't have any idea where or how. If somebody finds the files helpful, here they are: https://transfer.sh/1E1MGxo/twig.tar.gz

The locations of which file should go where are in the twig-files.png.

**Comment by andymnc** [comment]
same here

**Comment by glhez** [comment]
The Twig Eclipse Plugin/Feature `com.dubture.twig.feature` seems to have been removed from [http://p2.pdt-extensions.org/](http://p2.pdt-extensions.org/) P2 update site.
I don't know why, however http://twig.dubture.com/ is not accessible either. Also, the repository use bintray to release, so it most likely the same problems that appear with other Maven/Eclipse plugin such as freemarker.

Alternatively, I've pushed a PR https://github.com/pulse00/Twig-Eclipse-Plugin/pull/105 but this will enforce Java 11 + Eclipse 2021.06 (probably, because I've use the P2 update site for this version; this may work with older version).

**Comment by o-alquimista** [comment]
How long until we can install it from the marketplace? I just tried again now and it's still unavailable.

**Comment by pounard** [comment]
It's not working for me either, since Eclipse upgrade to Version: 2021-06 (4.20.0).

Neither pdt extensions or market place are working.

**Comment by vardumper** [comment]
Same here. Not working. Neither on Windows nor MacOS.

**Comment by Mecanik** [comment]
This is crazy, such a great plugin and we can't install it...

**Comment by olberger** [comment]
> 
> Alternatively, I've pushed a PR #105 but this will enforce Java 11 + Eclipse 2021.06 (probably, because I've use the P2 update site for this version; this may work with older version).

People affected by this issue might want to experiment with the suggestion documented in PR #105 AFAIU

**Comment by cicob** [comment]
> > Alternatively, I've pushed a PR #105 but this will enforce Java 11 + Eclipse 2021.06 (probably, because I've use the P2 update site for this version; this may work with older version).
> 
> People affected by this issue might want to experiment with the suggestion documented in PR #105 AFAIU

Ohh, seems messy. Whan can we expect the simple installation to work again? I.e. what dependencies do you foresee in the build-path?

**Comment by skynet** [comment]
Works in Eclipse using this solution: https://github.com/pulse00/Twig-Eclipse-Plugin/pull/105
Thanks!

**Comment by manoj-apare** [comment]
New to Eclipse. Can someone list out the steps or guide me on how to install the twig plugin using PR #105

**Comment by zulus** [comment]
Fixed
