### ISSUE TITLE
Indentation settings : using space instead of tabs

### ISSUE THREAD

**Issue by antoinegomez** [pulse00/Twig-Eclipse-Plugin#68]
How is it possible to switch the indentation settings ?

Using Aptana, in the preferences I specified to use spaces for indentation, no config option for that in Twig editor.

**Comment by rudzboy** [comment]
+1

**Comment by pounard** [comment]
For what it worth, I am using a PHP codestyle with 2 as indentation, but twig remains with 4 spaces

**Comment by spantaleev** [comment]
For some reason, this plugin always indents using spaces for me, even though `Preferences -> PHP -> Code Style -> Formatter` says **Tab policy: Tab**.

At first, I thought that it might be ignoring the **Tab policy: Tab** setting and always using spaces (as specified in **Tab size**). However, changing **Tab size** doesn't affect the plugin.

.. so it seems like the plugin **always uses 4 spaces** and there's no way around that, unfortunately.

**Comment by zulus** [comment]
currently twig should use html editor settings, not php
