### ISSUE TITLE
PHP Explorer link with editor not working for *.twig

### ISSUE THREAD

**Issue by ihsanfaisal** [pulse00/Twig-Eclipse-Plugin#78]
Link with editor not working for *.twig file opened in PHP Explorer, but is working fine using Navigator and Project Explorer.

**Comment by yannickl88** [comment]
+1

**Comment by borgogelli** [comment]
very annoying :(

**Comment by efxexec** [comment]
+1 mmm hmmm

**Comment by zulus** [comment]
fixed in head
