### ISSUE TITLE
Cannot complete Installation

### ISSUE THREAD

**Issue by broncha** [pulse00/Twig-Eclipse-Plugin#79]
Hi,

I am trying to install this extension. I had downloaded Eclipse platform runtime 3.8.2, added the update site and first tried to install the PDT extension.

Other components are downloaded successfully, but it tries to download, `org.eclipse.dltk.ui_5.0.0.201310291609.jar` and `org.eclipse.dltk.core_5.0.0.201310291609.jar` from `https://hudson.eclipse.org/hudson/job/dltk-nightly/lastSuccessfulBuild/artifact/org.eclipse.dltk.releng/build/update.site/target/sites/plugins/` which never completes.. Both files are downloaded about 500 - 600 kb and just restarts downloading and just loops..

Its not the internet speed as I have fair speed as I just downloaded the runtime and other components..

**Comment by zulus** [comment]
Obsolete right now. PEX repositories no longer point to DLTK hudson snapshots.
