### ISSUE TITLE
Autocompletion not working for symfony paths.

### ISSUE THREAD

**Issue by jumika** [pulse00/Twig-Eclipse-Plugin#85]
When i type {{ path('[cursor is here]') }} and press ctrl + space there are two things that can happen:
autocomplete window come up with "no proposals" text or
error window come up with text: "Cannot access Source module Reason: Index out of bounds" ant than the autocomplete window with "no proposals" text.

**Comment by rtherry** [comment]
Same here.
PDT 3.7.0
No completion.
No route or parent block

**Comment by zulus** [comment]
I'm finishing twig editor refactoring (develop branch), this will be fixed here. First dev build in p2-dev update site should be available in next month.
