### ISSUE TITLE
Missing requirement: bundle org.eclipse.wst.sse.core

### ISSUE THREAD

**Issue by shakaran** [pulse00/Twig-Eclipse-Plugin#90]
I am trying to install this plugin in Aptana, but I get

	Cannot complete the install because one or more required items could not be found.
	  Software being installed: Twig Editor Feature 1.0.15.201510021243 (com.dubture.twig.feature.feature.group 1.0.15.201510021243)
	  Missing requirement: com.dubture.twig.core 1.0.15.201510021243 (com.dubture.twig.core 1.0.15.201510021243) requires 'bundle org.eclipse.wst.sse.core 0.0.0' but it could not be found
	  Cannot satisfy dependency:
		From: Twig Editor Feature 1.0.15.201510021243 (com.dubture.twig.feature.feature.group 1.0.15.201510021243)
		To: com.dubture.twig.core [1.0.15.201510021243]	

It is a problem from the plugin or the Aptana IDE? See too https://github.com/aptana/studio3/issues/358

**Comment by zulus** [comment]
You need eclipse update site. For example: `http://download.eclipse.org/releases/mars`
