### ISSUE TITLE
Does this work in Eclipse 4.6?

### ISSUE THREAD

**Issue by jacobweber** [pulse00/Twig-Eclipse-Plugin#93]
Does this or the Symfony plugin work in Eclipse 4.6?

I've tried installing both on Eclipse 4.6.0 for Mac OS 10.11.6, with PDT 4.0.1. I've tried installing the plugins from the dev repository and the Marketplace. After a restart, they show up in the Installation Details window, but they don't appear anywhere else, like in File Associations or Preferences. There's nothing in the .metadata/.log file about either one.

**Comment by zulus** [comment]
Yes works correctly on Eclipse 4.6. Require PDT 4.0/4.0.1
In preferences should be available Twig section.

How you install it? From marketplace as additional to PHP Package, or you are using different package?

**Comment by jacobweber** [comment]
I installed the Twig and Symfony plugins from the Marketplace button on your site. When that didn't work, I tried removing them and installing Symfony from both repository links on your site, and neither worked.

**Comment by jacobweber** [comment]
I tried re-installing Eclipse using the installer, then installing Symfony from the Marketplace, and it worked. So there must be something wrong with my old app's configuration. I'll close this.

**Comment by zulus** [comment]
Thanks!
